local addonName, addon = ...

local Presets = addon.Presets
if not Presets or not Presets.Register then
    error("ScooterMod preset payload loaded before Presets API (core/presets.lua). Check ScooterMod.toc load order: core/presets.lua must load before core/preset_*.lua.", 2)
end

Presets:Register({
    id = "ScooterUI",
    name = "ScooterUI",
    description = "Author's flagship desktop layout showcasing ScooterMod styling for raiding and Mythic+.",
    wowBuild = "11.2.5",
    version = "2025.12.23",
    screenClass = "desktop",
    recommendedInput = "Mouse + Keyboard",
    tags = { "Desktop", "Mythic+", "Raiding" },
    previewTexture = "Interface\\AddOns\\ScooterMod\\Scooter",
    previewThumbnail = "Interface\\AddOns\\ScooterMod\\Scooter",
    designedFor = { "Optimized for 4k 16:9 monitors", "Competitive PvE content, M+ and Raid" },
    recommends = { "Baganator", "Chattynator", "Platynator" },
    lastUpdated = "2025-12-23",

    -- Edit Mode layout payload (raw layoutInfo table).
    -- Capture/update via: /scoot debug editmode export "ScooterUI"
    -- NOTE: We intentionally do NOT ship the Blizzard Share string because there is no import API.
    -- EDITMODE_LAYOUT_START
    editModeLayout = {
      layoutName = "ScooterUI",
      layoutType = 2,
      systems = {
    {
      anchorInfo = {
        offsetX = 0,
        offsetY = -575,
        point = "CENTER",
        relativePoint = "CENTER",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 2,
        },
        {
          setting = 2,
          value = 12,
        },
        {
          setting = 3,
          value = 0,
        },
        {
          setting = 4,
          value = 2,
        },
        {
          setting = 6,
          value = 1,
        },
        {
          setting = 8,
          value = 1,
        },
        {
          setting = 9,
          value = 1,
        },
      },
      system = 0,
      systemIndex = 1,
    },
    {
      anchorInfo = {
        offsetX = 150,
        offsetY = -575,
        point = "CENTER",
        relativePoint = "CENTER",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 2,
        },
        {
          setting = 2,
          value = 12,
        },
        {
          setting = 3,
          value = 0,
        },
        {
          setting = 4,
          value = 2,
        },
        {
          setting = 5,
          value = 0,
        },
        {
          setting = 9,
          value = 1,
        },
      },
      system = 0,
      systemIndex = 2,
    },
    {
      anchorInfo = {
        offsetX = 300,
        offsetY = -575,
        point = "CENTER",
        relativePoint = "CENTER",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 2,
        },
        {
          setting = 2,
          value = 12,
        },
        {
          setting = 3,
          value = 0,
        },
        {
          setting = 4,
          value = 2,
        },
        {
          setting = 5,
          value = 0,
        },
        {
          setting = 9,
          value = 1,
        },
      },
      system = 0,
      systemIndex = 3,
    },
    {
      anchorInfo = {
        offsetX = -150,
        offsetY = -575,
        point = "CENTER",
        relativePoint = "CENTER",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 2,
        },
        {
          setting = 2,
          value = 12,
        },
        {
          setting = 3,
          value = 0,
        },
        {
          setting = 4,
          value = 2,
        },
        {
          setting = 5,
          value = 0,
        },
        {
          setting = 9,
          value = 1,
        },
      },
      system = 0,
      systemIndex = 4,
    },
    {
      anchorInfo = {
        offsetX = -300,
        offsetY = -575,
        point = "CENTER",
        relativePoint = "CENTER",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 2,
        },
        {
          setting = 2,
          value = 12,
        },
        {
          setting = 3,
          value = 0,
        },
        {
          setting = 4,
          value = 2,
        },
        {
          setting = 5,
          value = 0,
        },
        {
          setting = 9,
          value = 1,
        },
      },
      system = 0,
      systemIndex = 5,
    },
    {
      anchorInfo = {
        offsetX = 328,
        offsetY = -1102,
        point = "TOP",
        relativePoint = "TOP",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 2,
        },
        {
          setting = 2,
          value = 12,
        },
        {
          setting = 3,
          value = 0,
        },
        {
          setting = 4,
          value = 2,
        },
        {
          setting = 5,
          value = 0,
        },
        {
          setting = 9,
          value = 1,
        },
      },
      system = 0,
      systemIndex = 6,
    },
    {
      anchorInfo = {
        offsetX = 0,
        offsetY = 150,
        point = "CENTER",
        relativePoint = "CENTER",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 1,
        },
        {
          setting = 2,
          value = 12,
        },
        {
          setting = 3,
          value = 5,
        },
        {
          setting = 4,
          value = 2,
        },
        {
          setting = 5,
          value = 0,
        },
        {
          setting = 9,
          value = 1,
        },
      },
      system = 0,
      systemIndex = 7,
    },
    {
      anchorInfo = {
        offsetX = 0,
        offsetY = 200,
        point = "CENTER",
        relativePoint = "CENTER",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 1,
        },
        {
          setting = 2,
          value = 12,
        },
        {
          setting = 3,
          value = 5,
        },
        {
          setting = 4,
          value = 2,
        },
        {
          setting = 5,
          value = 0,
        },
        {
          setting = 9,
          value = 1,
        },
      },
      system = 0,
      systemIndex = 8,
    },
    {
      anchorInfo = {
        offsetX = -4,
        offsetY = 0,
        point = "BOTTOMRIGHT",
        relativePoint = "BOTTOMLEFT",
        relativeTo = "MultiBarLeft",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 1,
        },
        {
          setting = 3,
          value = 1,
        },
        {
          setting = 4,
          value = 2,
        },
      },
      system = 0,
      systemIndex = 11,
    },
    {
      anchorInfo = {
        offsetX = -5,
        offsetY = 4,
        point = "TOPRIGHT",
        relativePoint = "BOTTOMRIGHT",
        relativeTo = "PetFrame",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 1,
        },
        {
          setting = 3,
          value = 0,
        },
        {
          setting = 4,
          value = 2,
        },
        {
          setting = 9,
          value = 1,
        },
      },
      system = 0,
      systemIndex = 12,
    },
    {
      anchorInfo = {
        offsetX = 286.5,
        offsetY = 265.5,
        point = "BOTTOMLEFT",
        relativePoint = "BOTTOMLEFT",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 1,
        },
        {
          setting = 3,
          value = 5,
        },
        {
          setting = 4,
          value = 2,
        },
      },
      system = 0,
      systemIndex = 13,
    },
    {
      anchorInfo = {
        offsetX = 0,
        offsetY = -292.79998779297,
        point = "CENTER",
        relativePoint = "CENTER",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 2,
        },
        {
          setting = 1,
          value = 0,
        },
        {
          setting = 2,
          value = 0,
        },
      },
      system = 1,
    },
    {
      anchorInfo = {
        offsetX = 882.70001220703,
        offsetY = -2,
        point = "TOP",
        relativePoint = "TOP",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 0,
        },
        {
          setting = 2,
          value = 11,
        },
      },
      system = 2,
    },
    {
      anchorInfo = {
        offsetX = -413.29998779297,
        offsetY = -775.5,
        point = "TOP",
        relativePoint = "TOP",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 1,
          value = 0,
        },
        {
          setting = 16,
          value = 15,
        },
      },
      system = 3,
      systemIndex = 1,
    },
    {
      anchorInfo = {
        offsetX = 417.20001220703,
        offsetY = -775.5,
        point = "TOP",
        relativePoint = "TOP",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 2,
          value = 1,
        },
        {
          setting = 16,
          value = 15,
        },
      },
      system = 3,
      systemIndex = 2,
    },
    {
      anchorInfo = {
        offsetX = 223.60000610352,
        offsetY = 198.19999694824,
        point = "CENTER",
        relativePoint = "CENTER",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 2,
          value = 1,
        },
        {
          setting = 3,
          value = 1,
        },
        {
          setting = 16,
          value = 10,
        },
      },
      system = 3,
      systemIndex = 3,
    },
    {
      anchorInfo = {
        offsetX = 829.70001220703,
        offsetY = -922,
        point = "TOPLEFT",
        relativePoint = "TOPLEFT",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 4,
          value = 1,
        },
        {
          setting = 5,
          value = 0,
        },
        {
          setting = 6,
          value = 1,
        },
        {
          setting = 10,
          value = 22,
        },
        {
          setting = 11,
          value = 24,
        },
        {
          setting = 12,
          value = 0,
        },
        {
          setting = 14,
          value = 1,
        },
        {
          setting = 16,
          value = 0,
        },
      },
      system = 3,
      systemIndex = 4,
    },
    {
      anchorInfo = {
        offsetX = 830.29998779297,
        offsetY = -918.20001220703,
        point = "TOPLEFT",
        relativePoint = "TOPLEFT",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 9,
          value = 0,
        },
        {
          setting = 10,
          value = 6,
        },
        {
          setting = 11,
          value = 6,
        },
        {
          setting = 12,
          value = 0,
        },
        {
          setting = 13,
          value = 0,
        },
        {
          setting = 14,
          value = 0,
        },
        {
          setting = 15,
          value = 5,
        },
      },
      system = 3,
      systemIndex = 5,
    },
    {
      anchorInfo = {
        offsetX = -604.09997558594,
        offsetY = -465,
        point = "TOPRIGHT",
        relativePoint = "TOPRIGHT",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 3,
          value = 0,
        },
        {
          setting = 7,
          value = 1,
        },
        {
          setting = 16,
          value = 0,
        },
      },
      system = 3,
      systemIndex = 6,
    },
    {
      anchorInfo = {
        offsetX = 0,
        offsetY = 0,
        point = "RIGHT",
        relativePoint = "RIGHT",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = true,
      settings = {
        {
          setting = 10,
          value = 0,
        },
        {
          setting = 11,
          value = 0,
        },
        {
          setting = 12,
          value = 0,
        },
        {
          setting = 17,
          value = 1,
        },
      },
      system = 3,
      systemIndex = 7,
    },
    {
      anchorInfo = {
        offsetX = -35.799999237061,
        offsetY = 29.5,
        point = "TOP",
        relativePoint = "BOTTOM",
        relativeTo = "PlayerFrame",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 16,
          value = 5,
        },
      },
      system = 3,
      systemIndex = 8,
    },
    {
      anchorInfo = {
        offsetX = 0,
        offsetY = 517.5,
        point = "CENTER",
        relativePoint = "CENTER",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
      },
      system = 4,
    },
    {
      anchorInfo = {
        offsetX = -457,
        offsetY = 402,
        point = "BOTTOM",
        relativePoint = "BOTTOM",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
      },
      system = 5,
    },
    {
      anchorInfo = {
        offsetX = -4,
        offsetY = 0,
        point = "TOPRIGHT",
        relativePoint = "TOPLEFT",
        relativeTo = "MinimapCluster",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 0,
        },
        {
          setting = 2,
          value = 0,
        },
        {
          setting = 3,
          value = 11,
        },
        {
          setting = 5,
          value = 5,
        },
        {
          setting = 6,
          value = 15,
        },
      },
      system = 6,
      systemIndex = 1,
    },
    {
      anchorInfo = {
        offsetX = 0,
        offsetY = -4,
        point = "TOPLEFT",
        relativePoint = "BOTTOMLEFT",
        relativeTo = "BuffFrame",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 0,
        },
        {
          setting = 2,
          value = 1,
        },
        {
          setting = 4,
          value = 10,
        },
        {
          setting = 5,
          value = 7,
        },
        {
          setting = 6,
          value = 15,
        },
      },
      system = 6,
      systemIndex = 2,
    },
    {
      anchorInfo = {
        offsetX = 223.39999389648,
        offsetY = 26.799999237061,
        point = "TOP",
        relativePoint = "BOTTOM",
        relativeTo = "FocusFrame",
      },
      isInDefaultPosition = false,
      settings = {
      },
      system = 7,
    },
    {
      anchorInfo = {
        offsetX = 35,
        offsetY = 50,
        point = "BOTTOMLEFT",
        relativePoint = "BOTTOMLEFT",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 4,
        },
        {
          setting = 1,
          value = 30,
        },
        {
          setting = 2,
          value = 1,
        },
        {
          setting = 3,
          value = 71,
        },
      },
      system = 8,
    },
    {
      anchorInfo = {
        offsetX = 0,
        offsetY = 4,
        point = "BOTTOMLEFT",
        relativePoint = "TOPLEFT",
        relativeTo = "EncounterBar",
      },
      isInDefaultPosition = false,
      settings = {
      },
      system = 9,
    },
    {
      anchorInfo = {
        offsetX = 16,
        offsetY = -116,
        point = "TOPLEFT",
        relativePoint = "TOPLEFT",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = true,
      settings = {
      },
      system = 10,
    },
    {
      anchorInfo = {
        offsetX = 860.59997558594,
        offsetY = 402,
        point = "BOTTOM",
        relativePoint = "BOTTOM",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
      },
      system = 11,
    },
    {
      anchorInfo = {
        offsetX = -904.70001220703,
        offsetY = 802,
        point = "BOTTOM",
        relativePoint = "BOTTOM",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 0,
        },
        {
          setting = 2,
          value = 0,
        },
      },
      system = 12,
    },
    {
      anchorInfo = {
        offsetX = 2,
        offsetY = -113.69999694824,
        point = "LEFT",
        relativePoint = "LEFT",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 1,
        },
        {
          setting = 1,
          value = 0,
        },
        {
          setting = 2,
          value = 0,
        },
        {
          setting = 3,
          value = 15,
        },
      },
      system = 13,
    },
    {
      anchorInfo = {
        offsetX = 520.5,
        offsetY = 1.5,
        point = "BOTTOM",
        relativePoint = "BOTTOM",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 0,
        },
        {
          setting = 2,
          value = 0,
        },
      },
      system = 14,
    },
    {
      anchorInfo = {
        offsetX = -455.79998779297,
        offsetY = -2,
        point = "TOP",
        relativePoint = "TOP",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
      },
      system = 15,
      systemIndex = 1,
    },
    {
      anchorInfo = {
        offsetX = 0,
        offsetY = 17,
        point = "BOTTOM",
        relativePoint = "BOTTOM",
        relativeTo = "StatusTrackingBarManager",
      },
      isInDefaultPosition = true,
      settings = {
      },
      system = 15,
      systemIndex = 2,
    },
    {
      anchorInfo = {
        offsetX = 0,
        offsetY = 0,
        point = "RIGHT",
        relativePoint = "RIGHT",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = true,
      settings = {
        {
          setting = 0,
          value = 5,
        },
      },
      system = 16,
    },
    {
      anchorInfo = {
        offsetX = 0,
        offsetY = -100,
        point = "TOP",
        relativePoint = "TOP",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = true,
      settings = {
        {
          setting = 0,
          value = 0,
        },
      },
      system = 17,
    },
    {
      anchorInfo = {
        offsetX = 0,
        offsetY = 0,
        point = "RIGHT",
        relativePoint = "RIGHT",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = true,
      settings = {
        {
          setting = 0,
          value = 10,
        },
      },
      system = 18,
    },
    {
      anchorInfo = {
        offsetX = 0,
        offsetY = 0,
        point = "BOTTOM",
        relativePoint = "BOTTOM",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = true,
      settings = {
        {
          setting = 0,
          value = 0,
        },
      },
      system = 19,
    },
    {
      anchorInfo = {
        offsetX = 0,
        offsetY = -242.19999694824,
        point = "CENTER",
        relativePoint = "CENTER",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 12,
        },
        {
          setting = 2,
          value = 1,
        },
        {
          setting = 3,
          value = 3,
        },
        {
          setting = 4,
          value = 6,
        },
        {
          setting = 5,
          value = 50,
        },
        {
          setting = 6,
          value = 0,
        },
        {
          setting = 8,
          value = 1,
        },
        {
          setting = 9,
          value = 1,
        },
        {
          setting = 10,
          value = 1,
        },
      },
      system = 20,
      systemIndex = 1,
    },
    {
      anchorInfo = {
        offsetX = 0,
        offsetY = -268.60000610352,
        point = "CENTER",
        relativePoint = "CENTER",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 0,
        },
        {
          setting = 1,
          value = 7,
        },
        {
          setting = 2,
          value = 1,
        },
        {
          setting = 3,
          value = 3,
        },
        {
          setting = 4,
          value = 6,
        },
        {
          setting = 5,
          value = 50,
        },
        {
          setting = 6,
          value = 0,
        },
        {
          setting = 8,
          value = 1,
        },
        {
          setting = 9,
          value = 1,
        },
        {
          setting = 10,
          value = 1,
        },
      },
      system = 20,
      systemIndex = 2,
    },
    {
      anchorInfo = {
        offsetX = 165.5,
        offsetY = 402,
        point = "BOTTOM",
        relativePoint = "BOTTOM",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 1,
        },
        {
          setting = 1,
          value = 1,
        },
        {
          setting = 2,
          value = 0,
        },
        {
          setting = 3,
          value = 3,
        },
        {
          setting = 4,
          value = 8,
        },
        {
          setting = 5,
          value = 50,
        },
        {
          setting = 6,
          value = 0,
        },
        {
          setting = 8,
          value = 1,
        },
        {
          setting = 9,
          value = 1,
        },
        {
          setting = 10,
          value = 1,
        },
      },
      system = 20,
      systemIndex = 3,
    },
    {
      anchorInfo = {
        offsetX = 0,
        offsetY = -140,
        point = "CENTER",
        relativePoint = "CENTER",
        relativeTo = "UIParent",
      },
      isInDefaultPosition = false,
      settings = {
        {
          setting = 0,
          value = 1,
        },
        {
          setting = 1,
          value = 1,
        },
        {
          setting = 2,
          value = 0,
        },
        {
          setting = 3,
          value = 5,
        },
        {
          setting = 4,
          value = 2,
        },
        {
          setting = 5,
          value = 50,
        },
        {
          setting = 6,
          value = 0,
        },
        {
          setting = 7,
          value = 2,
        },
        {
          setting = 8,
          value = 1,
        },
        {
          setting = 9,
          value = 1,
        },
        {
          setting = 10,
          value = 1,
        },
      },
      system = 20,
      systemIndex = 4,
    },
  },
    },
    -- EDITMODE_LAYOUT_END
    editModeSha256 = "PENDING",

    -- ScooterMod profile snapshot (captured from authoring machine).
    profileSha256 = "PENDING",
    -- SCOOTER_PROFILE_START
    scooterProfile = {    applyAll = {
      barTexturePending = "default",
      fontPending = "default",
      lastFontApplied = {
        changed = 102,
        timestamp = 1764607972,
        value = "ROBOTO_SEMICOND_BLACK",
      },
    },    components = {
      actionBar1 = {
        alwaysShowButtons = true,
        backdropDisable = false,
        backdropInset = 0,
        backdropOpacity = 100,
        backdropStyle = "blizzardBg",
        backdropTintColor = {
          1,
          1,
          1,
          1,
        },
        backdropTintEnable = false,
        barOpacity = 10,
        barOpacityOutOfCombat = 10,
        barOpacityWithTarget = 10,
        borderDisableAll = false,
        borderEnable = true,
        borderInset = 0,
        borderStyle = "square",
        borderThickness = 2,
        borderTintColor = {
          1,
          1,
          1,
          1,
        },
        borderTintEnable = false,
        columns = 2,
        hideBarArt = true,
        hideBarScrolling = true,
        iconPadding = 2,
        iconSize = 50,
        mouseoverMode = true,
        numIcons = 12,
        orientation = "H",
        positionX = 0,
        positionY = -575,
        supportsText = true,
        textCooldown = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textHotkey = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textHotkeyHidden = false,
        textMacro = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textMacroHidden = false,
        textStacks = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
      },
      actionBar2 = {
        alwaysShowButtons = true,
        backdropDisable = false,
        backdropInset = 0,
        backdropOpacity = 100,
        backdropStyle = "blizzardBg",
        backdropTintColor = {
          1,
          1,
          1,
          1,
        },
        backdropTintEnable = false,
        barOpacity = 10,
        barOpacityOutOfCombat = 10,
        barOpacityWithTarget = 10,
        barVisibility = "always",
        borderDisableAll = false,
        borderEnable = true,
        borderInset = 0,
        borderStyle = "square",
        borderThickness = 2,
        borderTintColor = {
          1,
          1,
          1,
          1,
        },
        borderTintEnable = false,
        columns = 2,
        iconPadding = 2,
        iconSize = 50,
        mouseoverMode = true,
        numIcons = 12,
        orientation = "H",
        positionX = 150,
        positionY = -575,
        supportsText = true,
        textCooldown = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textHotkey = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textHotkeyHidden = false,
        textMacro = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textMacroHidden = false,
        textStacks = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
      },
      actionBar3 = {
        alwaysShowButtons = true,
        backdropDisable = false,
        backdropInset = 0,
        backdropOpacity = 100,
        backdropStyle = "blizzardBg",
        backdropTintColor = {
          1,
          1,
          1,
          1,
        },
        backdropTintEnable = false,
        barOpacity = 10,
        barOpacityOutOfCombat = 10,
        barOpacityWithTarget = 10,
        barVisibility = "always",
        borderDisableAll = false,
        borderEnable = true,
        borderInset = 0,
        borderStyle = "square",
        borderThickness = 2,
        borderTintColor = {
          1,
          1,
          1,
          1,
        },
        borderTintEnable = false,
        columns = 2,
        iconPadding = 2,
        iconSize = 50,
        mouseoverMode = true,
        numIcons = 12,
        orientation = "H",
        positionX = 300,
        positionY = -575,
        supportsText = true,
        textCooldown = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textHotkey = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textHotkeyHidden = false,
        textMacro = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textMacroHidden = false,
        textStacks = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
      },
      actionBar4 = {
        alwaysShowButtons = true,
        backdropDisable = false,
        backdropInset = 0,
        backdropOpacity = 100,
        backdropStyle = "blizzardBg",
        backdropTintColor = {
          1,
          1,
          1,
          1,
        },
        backdropTintEnable = false,
        barOpacity = 10,
        barOpacityOutOfCombat = 10,
        barOpacityWithTarget = 10,
        barVisibility = "always",
        borderDisableAll = false,
        borderEnable = true,
        borderInset = 0,
        borderStyle = "square",
        borderThickness = 2,
        borderTintColor = {
          1,
          1,
          1,
          1,
        },
        borderTintEnable = false,
        columns = 2,
        iconPadding = 2,
        iconSize = 50,
        mouseoverMode = true,
        numIcons = 12,
        orientation = "H",
        positionX = -150,
        positionY = -575,
        supportsText = true,
        textCooldown = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textHotkey = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textHotkeyHidden = false,
        textMacro = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textMacroHidden = false,
        textStacks = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
      },
      actionBar5 = {
        alwaysShowButtons = true,
        backdropDisable = false,
        backdropInset = 0,
        backdropOpacity = 100,
        backdropStyle = "blizzardBg",
        backdropTintColor = {
          1,
          1,
          1,
          1,
        },
        backdropTintEnable = false,
        barOpacity = 10,
        barOpacityOutOfCombat = 10,
        barOpacityWithTarget = 10,
        barVisibility = "always",
        borderDisableAll = false,
        borderEnable = true,
        borderInset = 0,
        borderStyle = "square",
        borderThickness = 2,
        borderTintColor = {
          1,
          1,
          1,
          1,
        },
        borderTintEnable = false,
        columns = 2,
        iconPadding = 2,
        iconSize = 50,
        mouseoverMode = true,
        numIcons = 12,
        orientation = "H",
        positionX = -300,
        positionY = -575,
        supportsText = true,
        textCooldown = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textHotkey = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textHotkeyHidden = false,
        textMacro = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textMacroHidden = false,
        textStacks = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
      },
      actionBar6 = {
        alwaysShowButtons = true,
        backdropDisable = false,
        backdropInset = 0,
        backdropOpacity = 100,
        backdropStyle = "blizzardBg",
        backdropTintColor = {
          1,
          1,
          1,
          1,
        },
        backdropTintEnable = false,
        barOpacity = 100,
        barOpacityOutOfCombat = 10,
        barOpacityWithTarget = 100,
        barVisibility = "always",
        borderDisableAll = false,
        borderEnable = true,
        borderInset = 0,
        borderStyle = "square",
        borderThickness = 2,
        borderTintColor = {
          1,
          1,
          1,
          1,
        },
        borderTintEnable = false,
        columns = 2,
        iconPadding = 2,
        iconSize = 50,
        mouseoverMode = true,
        numIcons = 12,
        orientation = "H",
        positionX = 328,
        positionY = -525,
        supportsText = true,
        textCooldown = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textHotkey = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textHotkeyHidden = false,
        textMacro = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textMacroHidden = false,
        textStacks = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
      },
      actionBar7 = {
        alwaysShowButtons = true,
        backdropDisable = false,
        backdropInset = 0,
        backdropOpacity = 100,
        backdropStyle = "blizzardBg",
        backdropTintColor = {
          1,
          1,
          1,
          1,
        },
        backdropTintEnable = false,
        barOpacity = 100,
        barOpacityOutOfCombat = 100,
        barOpacityWithTarget = 100,
        barVisibility = "always",
        borderDisableAll = false,
        borderEnable = false,
        borderInset = 0,
        borderStyle = "square",
        borderThickness = 1,
        borderTintColor = {
          1,
          1,
          1,
          1,
        },
        borderTintEnable = false,
        columns = 1,
        iconPadding = 2,
        iconSize = 100,
        mouseoverMode = false,
        numIcons = 12,
        orientation = "H",
        positionX = 0,
        positionY = 150,
        supportsText = true,
        textCooldown = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "OUTLINE",
        },
        textHotkey = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textHotkeyHidden = false,
        textMacro = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textMacroHidden = false,
        textStacks = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "OUTLINE",
        },
      },
      actionBar8 = {
        alwaysShowButtons = true,
        backdropDisable = false,
        backdropInset = 0,
        backdropOpacity = 100,
        backdropStyle = "blizzardBg",
        backdropTintColor = {
          1,
          1,
          1,
          1,
        },
        backdropTintEnable = false,
        barOpacity = 100,
        barOpacityOutOfCombat = 100,
        barOpacityWithTarget = 100,
        barVisibility = "always",
        borderDisableAll = false,
        borderEnable = false,
        borderInset = 0,
        borderStyle = "square",
        borderThickness = 1,
        borderTintColor = {
          1,
          1,
          1,
          1,
        },
        borderTintEnable = false,
        columns = 1,
        iconPadding = 2,
        iconSize = 100,
        mouseoverMode = false,
        numIcons = 12,
        orientation = "H",
        positionX = 0,
        positionY = 200,
        supportsText = true,
        textCooldown = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "OUTLINE",
        },
        textHotkey = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textHotkeyHidden = false,
        textMacro = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textMacroHidden = false,
        textStacks = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "OUTLINE",
        },
      },
      buffs = {
        borderEnable = true,
        borderStyle = "square",
        borderThickness = 2,
        borderTintColor = {
          1,
          1,
          1,
          1,
        },
        borderTintEnable = false,
        direction = "left",
        hideCollapseButton = true,
        iconHeight = 24,
        iconLimit = 11,
        iconPadding = 15,
        iconSize = 100,
        iconWidth = 36,
        iconWrap = "down",
        opacity = 100,
        opacityOutOfCombat = 100,
        opacityWithTarget = 100,
        orientation = "H",
        positionX = 442,
        positionY = 516,
        supportsText = true,
        textCount = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textDuration = {
          color = {
            1,
            0.82352948188782,
            0,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 2,
            y = -2,
          },
          size = 12,
          style = "SHADOWTHICKOUTLINE",
        },
        textStacks = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
          },
          size = 14,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
      },
      debuffs = {
        direction = "right",
        iconHeight = 24,
        iconLimit = 8,
        iconPadding = 15,
        iconSize = 120,
        iconWidth = 35,
        iconWrap = "down",
        opacity = 100,
        opacityOutOfCombat = 100,
        opacityWithTarget = 100,
        orientation = "H",
        positionX = 457,
        positionY = 363,
        supportsText = true,
        textCount = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textDuration = {
          color = {
            1,
            0.82352948188782,
            0,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
          },
        },
        textStacks = {
          color = {
            1,
            1,
            1,
            1,
          },
          offset = {
          },
        },
      },
      essentialCooldowns = {
        borderEnable = true,
        borderInset = 0,
        borderStyle = "square",
        borderThickness = 3,
        borderTintColor = {
          1,
          1,
          1,
          1,
        },
        borderTintEnable = false,
        columns = 12,
        direction = "right",
        iconHeight = 32,
        iconPadding = 6,
        iconSize = 80,
        iconWidth = 48,
        opacity = 100,
        opacityOutOfCombat = 25,
        opacityWithTarget = 100,
        orientation = "H",
        positionX = 0,
        positionY = -242,
        showTimer = true,
        showTooltip = true,
        supportsText = true,
        textCharges = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textCooldown = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
          size = 24,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textDuration = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textName = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textStacks = {
          color = {
            1,
            0,
            0,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 12,
            y = 28,
          },
          size = 20,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        visibilityMode = "always",
      },
      microBar = {
        barOpacity = 1,
        barOpacityOutOfCombat = 20,
        barOpacityWithTarget = 1,
        direction = "up",
        eyeSize = 125,
        menuSize = 70,
        mouseoverMode = true,
        orientation = "V",
        positionX = -1037,
        positionY = -114,
      },
      objectiveTracker = {
        height = 400,
        opacity = 0,
        opacityInCombat = 10,
        textHeader = {
          color = {
            0,
            1,
            0,
            1,
          },
          colorMode = "custom",
          fontFace = "ROBOTO_SEMICOND_BLACK",
          style = "THICKOUTLINE",
        },
        textQuestName = {
          color = {
            0,
            1,
            0,
            1,
          },
          colorMode = "custom",
          fontFace = "ROBOTO_SEMICOND_BLACK",
          style = "OUTLINE",
        },
        textQuestObjective = {
          color = {
            0.8,
            0.8,
            0.8,
            1,
          },
          colorMode = "default",
          fontFace = "ROBOTO_SEMICOND_BLACK",
          style = "OUTLINE",
        },
        textSize = 12,
        tintHeaderBackgroundColor = {
          0,
          1,
          0,
          0.50607621669769,
        },
        tintHeaderBackgroundEnable = true,
      },
      petBar = {
        alwaysShowButtons = true,
        backdropDisable = false,
        backdropInset = 0,
        backdropOpacity = 100,
        backdropStyle = "blizzardBg",
        backdropTintColor = {
          1,
          1,
          1,
          1,
        },
        backdropTintEnable = false,
        barOpacity = 100,
        barOpacityOutOfCombat = 10,
        barOpacityWithTarget = 10,
        borderDisableAll = false,
        borderEnable = true,
        borderInset = 0,
        borderStyle = "square",
        borderThickness = 3,
        borderTintColor = {
          1,
          1,
          1,
          1,
        },
        borderTintEnable = false,
        columns = 2,
        iconPadding = 2,
        iconSize = 50,
        mouseoverMode = true,
        orientation = "H",
        positionX = -444,
        positionY = -398,
        supportsText = true,
        textCooldown = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textHotkey = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textHotkeyHidden = false,
        textMacro = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 14,
          style = "OUTLINE",
        },
        textMacroHidden = false,
        textStacks = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 0,
            y = 0,
          },
          size = 16,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
      },
      sctDamage = {
        fontFace = "ROBOTO_SEMICOND_BLACK",
        fontScale = 60,
      },
      stanceBar = {
        barOpacity = 20,
        barOpacityOutOfCombat = 10,
        barOpacityWithTarget = 20,
        columns = 1,
        iconPadding = 2,
        iconSize = 60,
        mouseoverMode = true,
        orientation = "H",
        positionX = -469,
        positionY = -589,
      },
      tooltip = {
        fontFace = "ROBOTO_SEMICOND_BLACK",
        hideHealthBar = true,
        supportsText = true,
        textComparison = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
          size = 12,
          style = "OUTLINE",
        },
        textEverythingElse = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
          size = 12,
          style = "OUTLINE",
        },
        textLine2 = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textLine3 = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textLine4 = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textLine5 = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textLine6 = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textLine7 = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textTitle = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
          size = 20,
          style = "THICKOUTLINE",
        },
      },
      trackedBars = {
        barWidth = 170,
        borderEnable = true,
        borderStyle = "square",
        borderThickness = 2,
        borderTintColor = {
          1,
          1,
          1,
          1,
        },
        borderTintEnable = false,
        displayMode = "name",
        hideWhenInactive = true,
        iconBarPadding = 5,
        iconBorderEnable = true,
        iconBorderStyle = "square",
        iconBorderThickness = 2,
        iconBorderTintColor = {
          1,
          1,
          1,
          1,
        },
        iconBorderTintEnable = false,
        iconHeight = 20,
        iconPadding = 2,
        iconSize = 100,
        iconWidth = 32,
        opacity = 100,
        opacityOutOfCombat = 100,
        opacityWithTarget = 100,
        positionX = 0,
        positionY = -140,
        showTimer = true,
        showTooltip = true,
        styleBackgroundColor = {
          1,
          1,
          1,
          0.9,
        },
        styleBackgroundOpacity = 50,
        styleBackgroundTexture = "a1",
        styleEnableCustom = true,
        styleForegroundColor = {
          1,
          1,
          1,
          1,
        },
        styleForegroundTexture = "a1",
        supportsText = true,
        textCharges = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textCooldown = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textDuration = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textName = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
          size = 12,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textStacks = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        visibilityMode = "always",
      },
      trackedBuffs = {
        borderEnable = true,
        borderInset = 0,
        borderStyle = "square",
        borderThickness = 3,
        borderTintColor = {
          1,
          1,
          1,
          1,
        },
        borderTintEnable = false,
        direction = "down",
        hideWhenInactive = true,
        iconHeight = 32,
        iconPadding = 8,
        iconSize = 80,
        iconWidth = 48,
        opacity = 100,
        opacityOutOfCombat = 50,
        opacityWithTarget = 100,
        orientation = "V",
        positionX = 165,
        positionY = -121,
        showTimer = true,
        showTooltip = true,
        supportsText = true,
        textCharges = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textCooldown = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
          size = 18,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textDuration = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textName = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textStacks = {
          color = {
            1,
            0,
            0,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = -35,
          },
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        visibilityMode = "always",
      },
      utilityCooldowns = {
        borderEnable = true,
        borderInset = 0,
        borderStyle = "square",
        borderThickness = 2,
        borderTintColor = {
          1,
          1,
          1,
          1,
        },
        borderTintEnable = false,
        columns = 7,
        direction = "right",
        hideWhenInactive = true,
        iconHeight = 24,
        iconPadding = 6,
        iconSize = 80,
        iconWidth = 36,
        opacity = 100,
        opacityOutOfCombat = 25,
        opacityWithTarget = 100,
        orientation = "H",
        positionX = 0,
        positionY = -269,
        showTimer = true,
        showTooltip = true,
        supportsText = true,
        textCharges = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textCooldown = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textDuration = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textName = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textStacks = {
          color = {
            1,
            0,
            0,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 10,
            y = 4,
          },
          size = 14,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        visibilityMode = "always",
      },
    },
    groupFrames = {
      raid = {
        healthBarBackgroundColorMode = "default",
        healthBarBackgroundOpacity = 50,
        healthBarBackgroundTexture = "a3",
        healthBarBackgroundTint = {
          0,
          0,
          0,
          1,
        },
        healthBarColorMode = "default",
        healthBarTexture = "a3",
        healthBarTint = {
          1,
          1,
          1,
          1,
        },
        textPlayerName = {
          color = {
            1,
            1,
            1,
            1,
          },
          fontFace = "ROBOTO_SEMICOND_REG",
          offset = {
            x = 0,
            y = 0,
          },
          size = 8,
          style = "OUTLINE",
        },
      },
    },
    minimap = {
      hide = false,
      minimapPos = 162.4444425305,
    },
    ruleBaselines = {
      ["prdPower.hideBar"] = false,
      ["ufPlayerClassResource.hide"] = false,
      ["ufTargetFocus.levelTextHidden"] = true,
    },
    rules = {
      {
        action = {
          value = true,
        },
        displayIndex = 1,
        enabled = true,
        id = "rule-0001",
        trigger = {
          specIds = {
            63,
          },
          type = "specialization",
        },
      },
      {
        action = {
          id = "ufTargetFocus.levelTextHidden",
          value = true,
        },
        displayIndex = 2,
        enabled = true,
        id = "rule-0003",
        trigger = {
          level = 80,
          type = "playerLevel",
        },
      },
      {
        action = {
          id = "ufPlayerClassResource.hide",
          value = true,
        },
        displayIndex = 3,
        enabled = true,
        id = "rule-0004",
        trigger = {
          specIds = {
            262,
            263,
            264,
          },
          type = "specialization",
        },
      },
    },
    rulesState = {
      baselines = {
      },
      nextId = 5,
    },
    unitFrames = {
      Focus = {
        buffsDebuffs = {
          borderEnable = true,
          borderThickness = 2,
          hideBuffsDebuffs = true,
          iconHeight = 24,
          iconScale = 50,
          iconWidth = 32,
        },
        castBar = {
          anchorMode = "healthBottom",
          castBarBackgroundOpacity = 60,
          castBarBackgroundTexture = "a1",
          castBarBorderEnable = true,
          castBarBorderInset = 0,
          castBarBorderThickness = 1,
          castBarScale = 125,
          castBarSparkHidden = true,
          castBarTexture = "a1",
          castTimeText = {
            fontFace = "ROBOTO_SEMICOND_BLACK",
          },
          hideSpellNameBorder = true,
          iconBarPadding = 2,
          iconBorderEnable = true,
          iconBorderThickness = 1,
          iconDisabled = true,
          iconHeight = 12,
          iconWidth = 21,
          offsetY = -5,
          spellNameText = {
            fontFace = "ROBOTO_SEMICOND_BLACK",
            size = 6,
            style = "SHADOWOUTLINE",
          },
          widthPct = 55,
        },
        healthBarBackgroundTexture = "a1",
        healthBarBorderStyle = "square",
        healthBarBorderThickness = 1,
        healthBarTexture = "a1",
        levelTextHidden = true,
        misc = {
        },
        portrait = {
          hidePortrait = true,
        },
        powerBarHidden = true,
        scaleMult = 1.2000000476837,
        textHealthPercent = {
          alignment = "LEFT",
          color = {
            1,
            1,
            1,
            0.8203125,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
          },
          size = 8,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textHealthValue = {
          alignment = "RIGHT",
          color = {
            1,
            1,
            1,
            0.81163185834885,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
          },
          size = 8,
          style = "SHADOWTHICKOUTLINE",
        },
        textLevel = {
          color = {
            1,
            1,
            1,
            1,
          },
          colorMode = "custom",
          fontFace = "ROBOTO_SEMICOND_BLACK",
          size = 10,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textName = {
          alignment = "RIGHT",
          colorMode = "default",
          containerWidthPct = 100,
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            y = 0,
          },
          size = 10,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textPowerPercent = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textPowerValue = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        useCustomBorders = true,
      },
      Pet = {
        healthBarBackgroundTexture = "a1",
        healthBarBorderStyle = "square",
        healthBarBorderThickness = 1,
        healthBarTexture = "a1",
        healthValueHidden = true,
        levelTextHidden = true,
        opacityOutOfCombat = 25,
        portrait = {
          damageTextDisabled = true,
          hidePortrait = true,
        },
        powerBarHidden = true,
        scaleMult = 1.2000000476837,
        textHealthPercent = {
          alignment = "RIGHT",
          color = {
            1,
            1,
            1,
            0.8203125,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
          },
          size = 6,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textHealthValue = {
          alignment = "LEFT",
          color = {
            1,
            1,
            1,
            0.81163185834885,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
          },
          style = "SHADOWTHICKOUTLINE",
        },
        textLevel = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textName = {
          colorMode = "default",
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            y = 0,
          },
          size = 8,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textPowerPercent = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
          size = 8,
        },
        textPowerValue = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        useCustomBorders = true,
      },
      Player = {
        altPowerBar = {
          backgroundTexture = "a1",
          borderThickness = 1,
          offsetX = 32,
          offsetY = 8,
          textPercent = {
            alignment = "CENTER",
            fontFace = "ROBOTO_SEMICOND_BLACK",
            offset = {
              x = 0,
            },
            size = 6,
            style = "SHADOWOUTLINE",
          },
          textValue = {
            fontFace = "ROBOTO_SEMICOND_BLACK",
            size = 6,
            style = "SHADOWOUTLINE",
          },
          texture = "a1",
          valueHidden = true,
          widthPct = 50,
        },
        castBar = {
          castBarBackgroundOpacity = 70,
          castBarBackgroundTexture = "a1",
          castBarBorderEnable = true,
          castBarBorderThickness = 2,
          castBarColorMode = "class",
          castBarSparkHidden = true,
          castBarTexture = "a1",
          castTimeText = {
            fontFace = "ROBOTO_SEMICOND_BLACK",
          },
          hideChannelingShadow = true,
          hideTextBorder = true,
          spellNameText = {
            fontFace = "ROBOTO_SEMICOND_BLACK",
            size = 12,
            style = "SHADOWTHICKOUTLINE",
          },
          widthPct = 100,
        },
        classResource = {
          hide = true,
          offsetX = 0,
          offsetY = 0,
          scale = 50,
        },
        healthBarBackgroundTexture = "a2",
        healthBarBorderStyle = "square",
        healthBarBorderThickness = 1,
        healthBarBorderTintColor = {
          0,
          0,
          0,
          1,
        },
        healthBarBorderTintEnable = true,
        healthBarColorMode = "default",
        healthBarHideBorder = false,
        healthBarHideOverAbsorbGlow = true,
        healthBarTexture = "a2",
        levelTextHidden = true,
        misc = {
          hideGroupNumber = true,
          hideRoleIcon = true,
        },
        opacityOutOfCombat = 25,
        portrait = {
          damageText = {
            fontFace = "ROBOTO_SEMICOND_BLACK",
          },
          damageTextDisabled = true,
          hidePortrait = true,
        },
        powerBarBackgroundTexture = "a1",
        powerBarBorderThickness = 1,
        powerBarCustomPositionEnabled = true,
        powerBarHeightPct = 100,
        powerBarHidden = false,
        powerBarHideFullSpikes = true,
        powerBarHideSpark = true,
        powerBarOffsetX = 10,
        powerBarOffsetY = 0,
        powerBarPosX = 0,
        powerBarPosY = -65,
        powerBarTexture = "a1",
        powerBarWidthPct = 80,
        powerPercentHidden = true,
        scaleMult = 1,
        textHealthPercent = {
          alignment = "RIGHT",
          color = {
            1,
            1,
            1,
            0.8203125,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = -3,
          },
          size = 8,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textHealthValue = {
          alignment = "LEFT",
          color = {
            1,
            1,
            1,
            0.81163185834885,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 5,
          },
          size = 8,
          style = "SHADOWTHICKOUTLINE",
        },
        textLevel = {
          color = {
            1,
            1,
            1,
            1,
          },
          colorMode = "custom",
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            y = 1,
          },
          size = 10,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textName = {
          colorMode = "class",
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = -2,
            y = 2,
          },
          size = 12,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textPowerPercent = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        textPowerValue = {
          alignment = "CENTER",
          fontFace = "ROBOTO_SEMICOND_BLACK",
          size = 8,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        useCustomBorders = true,
      },
      Target = {
        buffsDebuffs = {
          borderEnable = true,
          borderThickness = 2,
          hideBuffsDebuffs = false,
          iconHeight = 21.000003814697,
          iconScale = 50,
          iconWidth = 32,
        },
        castBar = {
          anchorMode = "healthBottom",
          castBarBackgroundOpacity = 60,
          castBarBackgroundTexture = "a1",
          castBarBorderEnable = true,
          castBarBorderInset = 1,
          castBarBorderThickness = 1,
          castBarScale = 90,
          castBarSparkHidden = true,
          castBarTexture = "a1",
          hideSpellNameBorder = true,
          iconBarPadding = 2,
          iconBorderEnable = true,
          iconBorderThickness = 1,
          iconDisabled = true,
          iconHeight = 12,
          iconWidth = 21,
          offsetX = 0,
          offsetY = -5,
          spellNameText = {
            fontFace = "ROBOTO_SEMICOND_BLACK",
            offset = {
              y = 0,
            },
            size = 8,
            style = "SHADOWOUTLINE",
          },
          widthPct = 70,
        },
        healthBarBackgroundTexture = "a2",
        healthBarBorderStyle = "square",
        healthBarBorderThickness = 1,
        healthBarColorMode = "default",
        healthBarReverseFill = true,
        healthBarTexture = "a2",
        levelTextHidden = true,
        misc = {
          hideThreatMeter = true,
        },
        portrait = {
          hidePortrait = true,
        },
        powerBarHidden = true,
        scaleMult = 1,
        textHealthPercent = {
          alignment = "LEFT",
          color = {
            1,
            1,
            1,
            0.8203125,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
          },
          size = 8,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textHealthValue = {
          alignment = "RIGHT",
          color = {
            1,
            1,
            1,
            0.81163185834885,
          },
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
          },
          size = 8,
          style = "SHADOWTHICKOUTLINE",
        },
        textLevel = {
          color = {
            1,
            1,
            1,
            1,
          },
          colorMode = "custom",
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            y = 1,
          },
          size = 10,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textName = {
          alignment = "RIGHT",
          color = {
            1,
            1,
            1,
            1,
          },
          colorMode = "custom",
          containerWidthPct = 100,
          fontFace = "ROBOTO_SEMICOND_BLACK",
          offset = {
            x = 3,
            y = 0,
          },
          size = 10,
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textPowerPercent = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
          style = "HEAVYSHADOWTHICKOUTLINE",
        },
        textPowerValue = {
          fontFace = "ROBOTO_SEMICOND_BLACK",
        },
        useCustomBorders = true,
      },
      TargetOfTarget = {
        healthBarBackgroundTexture = "a2",
        healthBarBorderStyle = "default",
        healthBarBorderThickness = 1,
        healthBarTexture = "a2",
        offsetX = -35,
        offsetY = 50,
        portrait = {
          hidePortrait = true,
        },
        powerBarHidden = true,
        scale = 0.60000002384186,
        textName = {
          alignment = "CENTER",
          fontFace = "ROBOTO_SEMICOND_BLACK",
          size = 10,
          style = "SHADOWOUTLINE",
        },
        useCustomBorders = true,
      },
    },
  },
    -- SCOOTER_PROFILE_END
})
