-- classauras/mage.lua - Mage class aura definitions
local addonName, addon = ...

local CA = addon.ClassAuras

CA.RegisterAuras("MAGE", {
    {
        id = "freezing",
        label = "Freezing",
        auraSpellId = 1221389,
        cdmSpellId = 1246769,  -- Shatter passive (CDM tracks Freezing stacks under this ID)
        cdmBorrow = true,
        unit = "target",
        filter = "HARMFUL|PLAYER",
        enableLabel = "Enable Freezing Stacks Tracker",
        enableDescription = "Show your target's Freezing stacks as a dedicated, customizable aura.",
        editModeName = "Freezing",
        defaultPosition = { point = "CENTER", x = 0, y = -200 },
        defaultBarColor = { 0.68, 0.85, 1.0, 1.0 },  -- frost blue
        elements = {
            { type = "text",    key = "stacks", source = "applications", baseSize = 24, justifyH = "RIGHT" },
            { type = "texture", key = "icon",   customPath = "Interface\\AddOns\\Scoot\\media\\classauras\\PixelSnowflake", defaultSize = { 32, 32 } },
            { type = "bar",     key = "stackBar", source = "applications", maxValue = 20, fillMode = "fill", defaultSize = { 120, 12 } },
        },
        settings = {
            enabled         = { type = "addon", default = false },
            scale           = { type = "addon", default = 100 },
            mode            = { type = "addon", default = "icon" },
            iconMode        = { type = "addon", default = "default" },
            textFont        = { type = "addon", default = "FRIZQT__" },
            textStyle       = { type = "addon", default = "OUTLINE" },
            textSize        = { type = "addon", default = 24 },
            textColor       = { type = "addon", default = { 0.68, 0.85, 1.0, 1.0 } },
            textPosition    = { type = "addon", default = "inside" },
            textOuterAnchor = { type = "addon", default = "RIGHT" },
            textInnerAnchor = { type = "addon", default = "CENTER" },
            hideFromCDM     = { type = "addon", default = true },
            hideText        = { type = "addon", default = false },
            textOffsetX     = { type = "addon", default = 0 },
            textOffsetY     = { type = "addon", default = 0 },
            iconShape       = { type = "addon", default = 0 },
            borderStyle     = { type = "addon", default = "none" },
            borderThickness = { type = "addon", default = 1 },
            borderInsetH    = { type = "addon", default = 0 },
            borderInsetV    = { type = "addon", default = 0 },
            borderTintEnable = { type = "addon", default = false },
            borderTintColor  = { type = "addon", default = { 1, 1, 1, 1 } },
            barWidth                = { type = "addon", default = 120 },
            barHeight               = { type = "addon", default = 12 },
            barForegroundTexture    = { type = "addon", default = "bevelled" },
            barForegroundColorMode  = { type = "addon", default = "custom" },
            barForegroundTint       = { type = "addon", default = { 0.68, 0.85, 1.0, 1.0 } },
            barBackgroundTexture    = { type = "addon", default = "bevelled" },
            barBackgroundColorMode  = { type = "addon", default = "custom" },
            barBackgroundTint       = { type = "addon", default = { 0, 0, 0, 1 } },
            barBackgroundOpacity    = { type = "addon", default = 50 },
            barBorderStyle          = { type = "addon", default = "none" },
            barBorderThickness      = { type = "addon", default = 1 },
            barBorderInsetH         = { type = "addon", default = 0 },
            barBorderInsetV         = { type = "addon", default = 0 },
            barBorderTintEnable     = { type = "addon", default = false },
            barBorderTintColor      = { type = "addon", default = { 1, 1, 1, 1 } },
            barPosition             = { type = "addon", default = "RIGHT" },
            barOffsetX              = { type = "addon", default = 0 },
            barOffsetY              = { type = "addon", default = 0 },
            opacityInCombat         = { type = "addon", default = 100 },
            opacityWithTarget       = { type = "addon", default = 100 },
            opacityOutOfCombat      = { type = "addon", default = 100 },
        },
    },
    {
        id = "arcaneSalvo",
        label = "Arcane Salvo",
        auraSpellId = 1242974,
        cdmSpellId = 384452,
        cdmBorrow = true,
        unit = "player",
        filter = "HELPFUL|PLAYER",
        enableLabel = "Enable Arcane Salvo Stacks Tracker",
        enableDescription = "Show your Arcane Salvo stacks as a dedicated, customizable aura.",
        editModeName = "Arcane Salvo",
        defaultPosition = { point = "CENTER", x = 0, y = -200 },
        defaultBarColor = { 0.58, 0.38, 0.93, 1.0 },  -- arcane purple
        elements = {
            { type = "text",    key = "stacks", source = "applications", baseSize = 24, justifyH = "RIGHT" },
            { type = "texture", key = "icon",   customPath = "Interface\\AddOns\\Scoot\\media\\classauras\\PixelArcane", defaultSize = { 32, 32 } },
            { type = "bar",     key = "stackBar", source = "applications", maxValue = 25, fillMode = "fill", defaultSize = { 120, 12 } },
        },
        settings = {
            enabled         = { type = "addon", default = false },
            scale           = { type = "addon", default = 100 },
            mode            = { type = "addon", default = "icon" },
            iconMode        = { type = "addon", default = "default" },
            textFont        = { type = "addon", default = "FRIZQT__" },
            textStyle       = { type = "addon", default = "OUTLINE" },
            textSize        = { type = "addon", default = 24 },
            textColor       = { type = "addon", default = { 0.58, 0.38, 0.93, 1.0 } },
            textPosition    = { type = "addon", default = "inside" },
            textOuterAnchor = { type = "addon", default = "RIGHT" },
            textInnerAnchor = { type = "addon", default = "CENTER" },
            hideFromCDM     = { type = "addon", default = true },
            hideText        = { type = "addon", default = false },
            textOffsetX     = { type = "addon", default = 0 },
            textOffsetY     = { type = "addon", default = 0 },
            iconShape       = { type = "addon", default = 0 },
            borderStyle     = { type = "addon", default = "none" },
            borderThickness = { type = "addon", default = 1 },
            borderInsetH    = { type = "addon", default = 0 },
            borderInsetV    = { type = "addon", default = 0 },
            borderTintEnable = { type = "addon", default = false },
            borderTintColor  = { type = "addon", default = { 1, 1, 1, 1 } },
            barWidth                = { type = "addon", default = 120 },
            barHeight               = { type = "addon", default = 12 },
            barForegroundTexture    = { type = "addon", default = "bevelled" },
            barForegroundColorMode  = { type = "addon", default = "custom" },
            barForegroundTint       = { type = "addon", default = { 0.58, 0.38, 0.93, 1.0 } },
            barBackgroundTexture    = { type = "addon", default = "bevelled" },
            barBackgroundColorMode  = { type = "addon", default = "custom" },
            barBackgroundTint       = { type = "addon", default = { 0, 0, 0, 1 } },
            barBackgroundOpacity    = { type = "addon", default = 50 },
            barBorderStyle          = { type = "addon", default = "none" },
            barBorderThickness      = { type = "addon", default = 1 },
            barBorderInsetH         = { type = "addon", default = 0 },
            barBorderInsetV         = { type = "addon", default = 0 },
            barBorderTintEnable     = { type = "addon", default = false },
            barBorderTintColor      = { type = "addon", default = { 1, 1, 1, 1 } },
            barPosition             = { type = "addon", default = "RIGHT" },
            barOffsetX              = { type = "addon", default = 0 },
            barOffsetY              = { type = "addon", default = 0 },
            opacityInCombat         = { type = "addon", default = 100 },
            opacityWithTarget       = { type = "addon", default = 100 },
            opacityOutOfCombat      = { type = "addon", default = 100 },
        },
    },
})
